<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0</InformationalVersion>
    <Product>WinMdConverter</Product>
    <Company>WinMdConverter</Company>
    <Copyright>Copyright (c) 2026 WinMdConverter</Copyright>
  </PropertyGroup>
</Project>
